INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (1, 'CLIENTE PC CONSUMIDOR FINAL UPDATE SUCESSO 1 OK', 'RUA 1', 'CURRAIS NOVOS', 'Caucaia', 1004, '60450040', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (2, 'CLIENTE PC CONSUMIDOR FINAL UPDATE OK BELEZA', 'RUA CARLOS MAGNO', 'MONTESE', 'Fortaleza', 93, '60410020', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (3, 'A C F NEGREIROS ALTERADO COM SUCESSO!', 'RUA 2', 'TABULEIRO', 'Tabuleiro do Norte', 100, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (4, 'A DE OLIVEIRA GOMES MERCEARIA ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 1023, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (5, 'A V C DE SOUSA ALIMENTOS  - EPP', 'RUA 2', 'QUALQUER', 'Quixeré', 12, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (6, 'ALEX JOSE DE ARAUJO LIMA MS', 'RUA 2', 'QUALQUER', 'Russas', 25, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (7, 'AMADEU RICARDO DE MATOS EPP', 'RUA 2', 'QUALQUER', 'Russas', 32, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (8, 'ANA MARIA PAULA DA SILVA LOPES MICROEMPR', 'RUA 2', 'QUALQUER', 'São João do Jaguaribe', 87, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (9, 'COMERCIAL MERCADINHO DO FRANGO LTDA - ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 45, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (10, 'SUPER ECONOMICO LTDA', 'RUA 2', 'QUALQUER', 'Tabuleiro do Norte', 101, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (11, 'MASTER DISTRIB. DE ALIMENTOS EIRELI ME', 'RUA 2', 'QUALQUER', 'Maracanaú', 103, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (12, 'ANTONIO EUDES SALES GOMES - ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 1005, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (13, 'ANTONIO FILGUEIRA GUIMARAES - ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 225, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (14, 'BRUMATI & BIZONHIN LTDA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 224, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (15, 'DANIELLE ALEXANDRE MAIA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 885, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (16, 'CLEISON JOSE F DE LIMA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 669, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (17, 'EDMAR SOUSA & FILHA LTDA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 554, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (18, 'E M DA SILVA MICROEMPRESA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 221, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (19, 'EDSON LIMA - ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 551, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (20, 'F G A SILVA DE SOUZA-ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 336, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (21, 'F J RIBEIRO FILHO ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 995, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (22, 'F J  VIEIRA DE LIMA ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 548, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (23, 'ANA CLAUDIA DA SILVA NOGUEIRA - EPP', 'RUA 2', 'QUALQUER', 'Russas', 221, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (24, 'AURELIANO RIBEIRO DA SILVA', 'RUA 2', 'QUALQUER', 'Russas', 554, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (25, 'ANTONIO ALDIZIO DE LIMA MICROEMPRESA', 'RUA 2', 'QUALQUER', 'Russas', 886, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (26, 'CERAMICA FROTA COMERCIO E INDUSTRIA LTDA', 'RUA 2', 'QUALQUER', 'Russas', 1124, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (27, 'CERAMICA IRMAOS GOMES IND. E COM. LTDA', 'RUA 2', 'QUALQUER', 'Russas', 205, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (28, 'FLORINDA RODRIGUES LIMA EPP', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 4005, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (29, 'FRANCISCA ALVES MONTEIRO', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 632, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (30, 'FRANCISCO AURINOR MAIA - MICROEMPRESA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 325, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (31, 'FREITAS & RODRIGUES COMERCIAL DE ALIMENT', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 652, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (32, 'GECILDO MOREIRA DE OLIVEIRA MS', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 458, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (33, 'SUPERMERCADO NOSSA FAMILIA LTDA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 856, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (34, 'H MOREIRA FILHO ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 652, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (35, 'D. FERNANDES DE LIMA - ME', 'RUA 2', 'QUALQUER', 'Russas', 654, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (36, 'J V MOREIRA DE MIRANDA MICROEMPRESA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 452, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (37, 'ELIANA SANTIAGO DE LIMA - EPP', 'RUA 2', 'QUALQUER', 'Russas', 2365, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (38, 'EVAMBERGUE FREIRE MOREIRA - EPP', 'RUA 2', 'QUALQUER', 'Russas', 4005, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (39, 'JANUETE HOLANDA MAIA - EPP', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 632, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (40, 'JOAO ARAUJO LIMA ME', 'RUA 2', 'QUALQUER', 'Quixeré', 325, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (41, 'F.D. OLIVEIRA ME', 'RUA 2', 'QUALQUER', 'Russas', 652, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (42, 'JOSE NILO DE LIMA MICROEMPRESA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 458, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (43, 'F N G SOMBRA MICROEMPRESA', 'RUA 2', 'QUALQUER', 'Russas', 856, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (44, 'F. RENE OLIVEIRA PINHEIRO', 'RUA 2', 'QUALQUER', 'Russas', 652, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (45, 'F VEUDO GONCALVES - ME', 'RUA 2', 'QUALQUER', 'Russas', 654, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (46, 'JURACI LIMA FERREIRA', 'RUA 2', 'QUALQUER', 'Russas', 452, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (47, 'FRANCIEUDO DE OLIVEIRA GONCALVES ME', 'RUA 2', 'QUALQUER', 'Russas', 2365, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (48, 'LIGIA REGINA ALVES NOGUEIRA MICROEMPRESA', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 10, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (49, 'FRANCISCA AMANDA SAMPAIO DA COSTA ME', 'RUA 2', 'QUALQUER', 'Russas', 11, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (50, 'LUCIANO GRANJA SENA ME', 'RUA 2', 'QUALQUER', 'Limoeiro do Norte', 12, '62960000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (52, 'MACHADO DE ASSIS', 'MNMNMNMNMNMNMNMNMNMNM', 'OOOOKKKKKOO', 'KLKLKLKLKLKLKLKL', 220, '600000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (53, 'BRUNO MAIA', 'NNNNNNNNNNNNNNNNNNNNNN', 'BBBBBBBBBBBBBBBBBBBBBBBBBB', 'BCCCCCCCCCCCCCCCCCCCC', 1111, '6300000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (54, 'PEDRO ALVARES CABRAL', 'HHHGHGHGHGHGHGHGHGHGHGHGHGHGHGHHGHGHG', 'BVBVBVBVBVBVBVBV', 'CVCVCVCVCVCC', 111, '61907020', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (55, 'D. PEDRO I', 'HHHGHGHGHGHGHGHGHGHGHGHGHGHGHGHHGHGHG', 'BVBVBVBVBVBVBVBV', 'CVCVCVCVCVCC', 111, '6000000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (56, 'MNMNMNMNMNMNMNMNMNMNMNMNMNNMNMNMNNMTESTE', 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBNNNNNNTESTE', 'NMMNBMNBMBNMBMBNBMBNMBBMNBMBMBTESTE', 'KJGKGHGJHJHJFGHFJGHFJGHJFGTESTE', 2221, '60000', 'CE', NULL);
INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, NUMERO, CEP, UF, FLG_ATIVO)
              VALUES (57, 'MARIA DOS ANJOS SILVA', 'RUA TESTE', 'BAIRRO TESTE', 'CIDADE TESTE', 2121, '6000000', 'CE', NULL);

COMMIT WORK;
