/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 19/09/2023 17:57:31          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'C:\Sistemas\MKData\Dados\fbclient.dll';

CREATE DATABASE 'C:\Sistemas\MKData\Dados\DBPEDIDO.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_CLIENTES_ID;
SET GENERATOR GEN_CLIENTES_ID TO 50;

CREATE GENERATOR GEN_NEW_TABLE_ID;
SET GENERATOR GEN_NEW_TABLE_ID TO 0;

CREATE GENERATOR GEN_PEDIDO_ID;
SET GENERATOR GEN_PEDIDO_ID TO 0;

CREATE GENERATOR GEN_PRODUTOS_ID;
SET GENERATOR GEN_PRODUTOS_ID TO 0;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CLIENTE_ENDERECO (
    ID             INTEGER NOT NULL,
    ID_CODCLIENTE  INTEGER,
    ENDERECO       VARCHAR(100),
    NUMERO         VARCHAR(10),
    CEP            VARCHAR(20),
    BAIRRO         VARCHAR(60),
    CIDADE         VARCHAR(60),
    ESTADO         VARCHAR(10),
    PAIS           VARCHAR(10)
);

CREATE TABLE CLIENTE_TELEFONE (
    ID                INTEGER NOT NULL,
    ID_CODCLIENTE     INTEGER,
    TELEFONE_CLIENTE  VARCHAR(20)
);

CREATE TABLE CLIENTES (
    CODIGO        INTEGER NOT NULL,
    NOME          VARCHAR(100) NOT NULL,
    TIPO          CHAR(1),
    CPFCNPJ       VARCHAR(30),
    RG            VARCHAR(20),
    DATACADASTRO  DATE,
    FLG_ATIVO     INTEGER
);

CREATE TABLE PEDIDO (
    ID            INTEGER NOT NULL,
    NUMPEDI       VARCHAR(10),
    DATA_EMISSAO  DATE,
    COD_CLIENTE   INTEGER NOT NULL,
    VALOR_TOTAL   NUMERIC(15,2)
);

CREATE TABLE PEDIDO_PRODUTOS (
    ID_PEDIDO       INTEGER NOT NULL,
    ID_PRODUTO      INTEGER NOT NULL,
    NUMPEDIDO       VARCHAR(10),
    QUANTIDADE      FLOAT,
    VALOR_UNITARIO  FLOAT,
    VALOR_TOTAL     INTEGER
);

CREATE TABLE PRODUTOS (
    ID            INTEGER NOT NULL,
    CODIGO_BAR    VARCHAR(13),
    DESCRICAO     VARCHAR(60),
    PRECO_COMPRA  NUMERIC(15,2),
    PRECO_VENDA   NUMERIC(15,2),
    QTD_ESTOQUE   NUMERIC(15,2)
);

CREATE TABLE PRODUTOS_IMAGENS (
    ID_PRODUTO   INTEGER NOT NULL,
    PATH_IMAGEM  VARCHAR(100)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CODIGO);
ALTER TABLE CLIENTE_ENDERECO ADD CONSTRAINT PK_CLIENTE_ENDERECO PRIMARY KEY (ID);
ALTER TABLE CLIENTE_TELEFONE ADD CONSTRAINT PK_CLIENTE_TELEFONE PRIMARY KEY (ID);
ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (ID);
ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE CLIENTE_ENDERECO ADD CONSTRAINT FK_CLIENTE_ENDERECO_CLI FOREIGN KEY (ID_CODCLIENTE) REFERENCES CLIENTES (CODIGO);
ALTER TABLE CLIENTE_TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE_CLI FOREIGN KEY (ID_CODCLIENTE) REFERENCES CLIENTES (CODIGO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_1 FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES (CODIGO);
ALTER TABLE PEDIDO_PRODUTOS ADD CONSTRAINT FK_PEDIDO_PRODUTOS_1 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID);
ALTER TABLE PEDIDO_PRODUTOS ADD CONSTRAINT FK_PEDIDO_PRODUTOS_2 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID);
ALTER TABLE PRODUTOS_IMAGENS ADD CONSTRAINT FK_PRODUTOS_IMAGENS_PRD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID);
